### ISSUE TITLE
Firebase firestore

### ISSUE THREAD

**Issue by terrytan8** [dievskiy/feedapp#6]
Can i ask this application can received data from firebase firestore? Because i see the source code and i cannot find it when initialize this app, some function like loaduserdata (). I going to make a calories counter without the room database. Is this can be done?

**Comment by dievskiy** [comment]
This app does utilise cloud firestore to store products and profiles. For example, [here](https://github.com/dievskiy/feedapp/blob/master/app/src/main/java/com/feedapp/app/data/repositories/DayRepository.kt#L232) you can see method that fetches Day object. However, Room is also utilised to provide offline usage and caching. I think you should look how firestore sdk (or whatever name it has) handles offline (e.g whether it creates some queue for requests) and design your app based on that. I also recommend to look into other similar open source apps as this project is not maintained anymore.

**Comment by terrytan8** [comment]
thank you very much
