### ISSUE TITLE
Some error i cannot figure out...

### ISSUE THREAD

**Issue by terrytan8** [dievskiy/feedapp#7]
Good day sir, I facing some issues when referring to this app, in the fragment_home_down_menu.xml, I open a <view> and give it an id and class attached to it, but when I back to the homeDownFragment, I was unable to get the binding.homeDownMenuViewpager, it says unresolved reference for it. But if I change it to <View> I can get the binding but the class in XML shows an unknown attribute class.

**Comment by terrytan8** [comment]
sorry missing two word, i open a view    / i change it to View

**Comment by dievskiy** [comment]
I don't think this relates to the application itself but rather data binding. fragment_home_down_menu element could be accessed in fragment as binding.homeDownMenuViewpager. Try cleaning and rebuilding your project.
